// Code generated by mockery v2.36.0. DO NOT EDIT.

package queue

import mock "github.com/stretchr/testify/mock"

// MockActiveMQApi is an autogenerated mock type for the MockActiveMQApi type
type MockActiveMQApi struct {
	mock.Mock
}

// Disconnect provides a mock function with given fields:
func (_m *MockActiveMQApi) Disconnect() {
	_m.Called()
}

// Publish provides a mock function with given fields: topic, message
func (_m *MockActiveMQApi) Publish(topic string, message string) error {
	ret := _m.Called(topic, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(topic, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewActiveMQApi creates a new instance of ActiveMQApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActiveMQApi(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockActiveMQApi {
	mock := &MockActiveMQApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
