name: Bygg og kjør tester

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.MD"
      - ".gitignore"

jobs:
  list-go-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.list-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - id: list-modules
        run: echo modules=$(echo "$(dirname $(find * -name 'go.mod'))" | jq -cnR '[inputs | select(length>0)]') >> $GITHUB_OUTPUT
  build-and-test:
    runs-on: ubuntu-latest
    needs: list-go-modules
    strategy:
      matrix:
        module: ${{ fromJson(needs.list-go-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: "Installere testverktøy"
        run: go install gotest.tools/gotestsum@v1.11.0
      - name: "Bygg og test"
        run: |
          cd "${{ matrix.module }}"
          go build -v ./...
          gotestsum
