name: Bygg PR og kjør tester

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.MD"
      - ".gitignore"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [aws, db, queue]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: "Installere testverktøy"
        run: go install gotest.tools/gotestsum@v1.11.0
      - name: "Bygg og test"
        run: |
          cd "${{ matrix.module }}"
          go build -v ./...
          gotestsum

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [aws, db, queue]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Lint ${{ matrix.module  }}
        continue-on-error: true
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ${{ matrix.module }}
