name: Release

on:
  workflow_dispatch:
    inputs:
      module:
        required: false
        default: "*"
        description: "Mappenavn til modul som skal oppdateres. Støtter globbing. La den være * for å oppdatere alle moduler."
      bump:
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  list-go-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.list-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - id: list-modules
        run: echo modules=$(echo "$(dirname $(find ${{ inputs.module }} -name 'go.mod'))" | jq -cnR '[inputs | select(length>0)]') >> $GITHUB_OUTPUT

  release-new-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: list-go-modules
    strategy:
      matrix:
        module: ${{ fromJson(needs.list-go-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache semver-tool
        id: cache-semver-tool
        uses: actions/cache@v3
        with:
          path: ~/semver
          key: semver

      - name: Last ned semver-tool
        if: steps.cache-semver-tool.outputs.cache-hit != 'true'
        run: |
          wget -O ~/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/3.4.0/src/semver
          chmod +x ~/semver

      - name: "Release ny ${{ inputs.bump }} version av ${{ matrix.module }}"
        run: |
          module="${{ matrix.module }}"
          bump="${{ inputs.bump }}"
          git fetch --prune --unshallow --tags
          # fetch e.g. module/v1.2.3
          previous_tag=$(git tag --list --sort=-version:refname "$module*" | head -n1)
          # trim module/v prefix
          previous_version=$(echo $previous_tag | sed -e "s/$module\/v//")
          if [ -z "$previous_version" ]; then
              previous_version="0.0.0"
          fi
          new_version=$(~/semver bump $bump $previous_version)
          git tag "$module/v$new_version"
          git push --tags
          echo "$module: $previous_version → $new_version"
